connectivity_measures:
  - correlation
  - plv
  - pli
  - aec

graph_metrics:
  - clustering
  - path_length
  - efficiency
  - modularity

lag: 12  # For directed connectivity (Granger/DTF)
window_size: 2.0  # seconds
overlap: 0.5  # 50% overlap
