# ERP extraction settings
epoch_window: [-0.2, 0.8]   # seconds relative to stimulus
baseline: [-0.2, 0.0]       # seconds
components:
  - name: P300
    channel_set: parietal
    window: [0.28, 0.5]
  - name: N400
    channel_set: centroparietal
    window: [0.35, 0.6]
